services:
    server:
        container_name: server
        image: server
        ports: 
            - "8761:8761"
    gateway:
        container_name: gateway
        image: gateway
        ports: 
            - "8080:8080"
        depends_on:
            - server
        environment:
            - eureka.client.serviceUrl.defaultZone=http://server:8761/eureka
    ms-users:
        container_name: ms-users
        image: users
        ports: 
            - "8081:8081"
        depends_on:
            - db_postgres_1
            - gateway
            - kafka
            - zookeeper
        environment:
            - spring.datasource.url=jdbc:postgresql://db_postgres_1:5432/postgres    
            - spring.datasource.username=postgres
            - spring.datasource.password=root
            - eureka.client.serviceUrl.defaultZone=http://server:8761/eureka
            - spring.kafka.bootstrap-servers=kafka:9092
    ms-cards:
        container_name: ms-cards
        image: cards
        ports: 
            - "8082:8082"
        depends_on:
            - db_postgres_2
            - gateway
            - kafka
            - zookeeper
        environment:
            - spring.datasource.url=jdbc:postgresql://db_postgres_2:5433/postgres    
            - spring.datasource.username=postgres
            - spring.datasource.password=root
            - eureka.client.serviceUrl.defaultZone=http://server:8761/eureka
            - spring.kafka.bootstrap-servers=kafka:9092
    ms-payments:
        container_name: ms-payments
        image: payments
        ports: 
            - "8083:8083"
        depends_on:
            - mongodb
            - gateway
            - kafka
            - zookeeper
        environment:
            - eureka.client.serviceUrl.defaultZone=http://server:8761/eureka
            - spring.data.mongodb.host=mongodb
            - spring.data.mongodb.port=27017
            - spring.data.mongodb.username=admin
            - spring.data.mongodb.password=admin
            - spring.data.mongodb.database=payments
            - spring.data.mongodb.authentication-database=admin
            - spring.data.mongodb.auto-index-creation=true
            - spring.kafka.bootstrap-servers=kafka:9092
    db_postgres_1:
        container_name: db_postgres_1
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: root 
        ports:
            - "54440:5432"
        command: -p 5432
    db_postgres_2:
        container_name: db_postgres_2
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: root 
            POSTGRES_PORT: 5433
        ports:
            - "54442:5433"
        command: -p 5433
    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        container_name: kafka
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    